### PR TITLE
add new images (relabeled) from #940

### PR DESCRIPTION
**Pull request by haverland**

### CODE REVIEW

**Comment by caco3** [comment]
@jomjol, @haverland what was the goal of this PR? (I am unsure how to interpret @jomjo's comment https://github.com/jomjol/AI-on-the-edge-device/issues/940#issuecomment-1225875871

**Comment by jomjol** [comment]
you can find the new tflite file in the repository. I will upload it in this repo later. You find the file here:
https://github.com/jomjol/neural-network-analog-needle-readout/raw/main/ana-class100_0130_s1q.tflite

**Comment by caco3** [comment]
ah, ok.
but did you add the 2 folders by accident?

**Comment by jomjol** [comment]
which folders?

**Comment by caco3** [comment]
In the PR:
grafik

**Comment by caco3** [comment]
https://github.com/jomjol/neural-network-analog-needle-readout/pull/10/files

**Comment by jomjol** [comment]
Don't get your point. But the way it works is: you integrate the new images into "data_raw_all", then you run the scipts (locally in a python environment) and upload the results.
For the user only the tflite-file is relevant.

**Comment by caco3** [comment]
ah, I see, you need to commit the files so they can be used in the Github action.

Sorry for the confusion!
And thanks, the new cnn seems to work great!

**Pull request merged**
